// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVC9V9a0R6afnZxSHzDdz-y37UE6wSfmA',
    appId: '1:1071139077218:web:fb5ca08ff59ce83a14a53b',
    messagingSenderId: '1071139077218',
    projectId: 'rate-your-teacher-962ee',
    authDomain: 'rate-your-teacher-962ee.firebaseapp.com',
    storageBucket: 'rate-your-teacher-962ee.appspot.com',
    measurementId: 'G-G4LX5GSBZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHfGWnv0cM4jBcNCXEL07CsKVapEFuoE',
    appId: '1:1071139077218:android:83313ea6553830f514a53b',
    messagingSenderId: '1071139077218',
    projectId: 'rate-your-teacher-962ee',
    storageBucket: 'rate-your-teacher-962ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkp4B7MXjKGtgEgirPjSqkuDg1ntf2iHY',
    appId: '1:1071139077218:ios:52fc0668b7124db614a53b',
    messagingSenderId: '1071139077218',
    projectId: 'rate-your-teacher-962ee',
    storageBucket: 'rate-your-teacher-962ee.appspot.com',
    iosBundleId: 'com.example.rateYourTeacher',
  );
}
